spring.application.name=packzo
server.port= 8081


# Configure H2 to use file-based storage, e.g., in a 'data' folder relative to the project
spring.datasource.url=jdbc:h2:file:./data/packzodb
spring.jpa.properties.hibernate.default_schema=packzo
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Optional: Set username (default is 'sa')
spring.datasource.username=sa
# Optional: Set password (default is empty)
spring.datasource.password=packzo
# Optional: Enable the H2 web console for browsing the database
spring.h2.console.enabled=true
# Optional: Customize the H2 console access path
spring.h2.console.path=/h2-console
spring.web.resources.add-mappings=true

# Optional JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update